version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: lonely-bag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: shopify
    volumes:
      - mongodb_data:/data/db
    networks:
      - lonely-bag-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: lonely-bag-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/shopify
      JWT_SECRET: your_jwt_secret_key_here_change_in_production
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - lonely-bag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lonely-bag-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - lonely-bag-network

volumes:
  mongodb_data:

networks:
  lonely-bag-network:
    driver: bridge 